language: php

php:
  - 5.5
  - 5.6
  - hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  - mysql -e 'create database score11;'

script: phpunit

services:
  - mysql