language: php

php:
  - 5.5
  - 5.6
  - hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  - mysql -e 'create database score11;'
  - php artisan migrate:install --no-interaction -vvv

script:
  - php artisan migrate --env=testing --no-interaction -vvv
  - phpunit

after_script:
  - php artisan migrate:rollback --env=testing --no-interaction -vvv

services:
  - mysql